-- MySQL Script generated by MySQL Workbench
-- Wed Mar  2 09:54:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_account` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`struttura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`struttura` (
  `idstruttura` INT NOT NULL AUTO_INCREMENT,
  `Citta` VARCHAR(45) NOT NULL,
  `Indirizzo` VARCHAR(45) NOT NULL,
  `Cap` VARCHAR(45) NOT NULL,
  `Capienza` INT(5) NOT NULL,
  `NumCamere` VARCHAR(100) NULL DEFAULT NULL,
  `DistanzaStrutt` VARCHAR(100) NULL DEFAULT NULL,
  `VicinanzaTra` VARCHAR(100) NULL DEFAULT NULL,
  `Parcheggio` TINYINT NULL DEFAULT NULL,
  `user_account_id_user` INT NOT NULL,
  PRIMARY KEY (`idstruttura`),
  INDEX `fk_struttura_user_account_idx` (`user_account_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_struttura_user_account`
    FOREIGN KEY (`user_account_id_user`)
    REFERENCES `mydb`.`user_account` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dati_questura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dati_questura` (
  `id_datiquestura` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `cognome_cliente` VARCHAR(45) NOT NULL,
  `documento_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_datiquestura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dati_ufficioturismo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dati_ufficioturismo` (
  `id_ufficioturismo` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `cognome_cliente` VARCHAR(45) NOT NULL,
  `documento_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ufficioturismo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dati_contabili`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dati_contabili` (
  `id_daticontabili` INT NOT NULL AUTO_INCREMENT,
  `costi` VARCHAR(45) NOT NULL,
  `ricavi` VARCHAR(45) NOT NULL,
  `mese` VARCHAR(45) NOT NULL,
  `totale` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_daticontabili`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clienti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clienti` (
  `id_clienti` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cognome` VARCHAR(45) NOT NULL,
  `codice_fiscale` VARCHAR(45) NOT NULL,
  `numero_documento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_clienti`),
  UNIQUE INDEX `numero_documento_UNIQUE` (`numero_documento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prenotazioni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prenotazioni` (
  `id_prenotazione` INT NOT NULL AUTO_INCREMENT,
  `codice_fiscale` VARCHAR(45) NOT NULL,
  `check_in` DATE NOT NULL,
  `check_out` DATE NOT NULL,
  `citta_struttura` VARCHAR(45) NOT NULL,
  `numero_persone` INT NOT NULL,
  `tipologia_camera` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_prenotazione`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recensione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recensione` (
  `id_recensione` INT NOT NULL AUTO_INCREMENT,
  `recensione` VARCHAR(45) NOT NULL,
  `risposta` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_recensione`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
